remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: otak-agent
description: AI-powered Desktop Assistant for Windows
show_downloads: true
google_analytics:
github:
  repository_url: https://github.com/tsuyoshi-otake/otak-agent
  zip_url: https://github.com/tsuyoshi-otake/otak-agent/releases
  tar_url: https://github.com/tsuyoshi-otake/otak-agent/releases